# Generated by Django 5.0.3 on 2024-03-22 23:50

import django.db.models.deletion
import psp_cash_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0003_alter_membre_sexep'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbcompagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_compagnie', models.CharField(blank=True, max_length=50, verbose_name='CODE COMPAGNIE ')),
                ('compagnie', models.CharField(blank=True, max_length=50, verbose_name='COMPAGNIE ')),
                ('adresse', models.CharField(blank=True, max_length=50, verbose_name='ADRESSE ')),
                ('adresse2', models.CharField(blank=True, max_length=50, verbose_name='ADRESSE ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('phone3', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('logoPath', models.FileField(blank=True, null=True, upload_to=psp_cash_app.models.filepath)),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='EMAIL ')),
                ('siteweb', models.CharField(blank=True, max_length=50, verbose_name='SITE ')),
            ],
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.CreateModel(
            name='tbdepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_departement', models.CharField(blank=True, max_length=50, verbose_name='CODE DEPARTEMENT ')),
                ('departement', models.CharField(blank=True, max_length=50, verbose_name='DEPARTEMENT ')),
                ('print_in_kitchen', models.CharField(blank=True, max_length=50, verbose_name='PRINT IN KITCHEN ')),
                ('print_bar', models.CharField(blank=True, max_length=50, verbose_name='PRINT BAR ')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie')),
            ],
        ),
        migrations.CreateModel(
            name='tbunitemesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_mesure', models.CharField(blank=True, max_length=50, verbose_name='UNITE DE MESURE ')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie')),
            ],
        ),
        migrations.CreateModel(
            name='tbarticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_articl', models.CharField(blank=True, max_length=50, verbose_name='CODE ARTICLE ')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='DESCRIPTION ')),
                ('description2', models.CharField(blank=True, max_length=50, verbose_name='DESCRIPTION ')),
                ('cout_unit', models.FloatField(blank=True, default='0.0', null=True, verbose_name='COUT')),
                ('quantite', models.FloatField(blank=True, default='0.0', null=True, verbose_name='QUANTITE')),
                ('prix', models.FloatField(blank=True, default='0.0', null=True, verbose_name='PRICE')),
                ('reoderpoint', models.FloatField(blank=True, default='0.0', null=True, verbose_name='REODERPOINT')),
                ('date_expiration', models.DateTimeField(verbose_name='Date Cotisation (YYYY-MM-DD)')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie')),
                ('code_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbdepartement')),
                ('unite_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbunitemesure')),
            ],
        ),
    ]
