# Generated by Django 5.0.3 on 2024-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0006_tbcompagnie_couleur_preferee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcompagnie',
            name='taux_interet',
        ),
        migrations.AddField(
            model_name='tbcompagnie',
            name='statut',
            field=models.CharField(blank=True, default='Enable', max_length=50, null=True, verbose_name='Status Compagnie'),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
