# Generated by Django 5.0.3 on 2024-03-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0007_remove_tbcompagnie_taux_interet_tbcompagnie_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='muso',
        ),
        migrations.AddField(
            model_name='customuser',
            name='compagnie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie'),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
