# Generated by Django 5.0.3 on 2024-03-24 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0008_remove_customuser_muso_customuser_compagnie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.CreateModel(
            name='tbemploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codeemp', models.CharField(blank=True, max_length=50, verbose_name='CODE EMPLOYE ')),
                ('nomemp', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOM EMPLOYE ')),
                ('prenomemp', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRENOM EMPLOYE ')),
                ('sexeemp', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE EMPLOYE ')),
                ('cinemp', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIN ')),
                ('nifemp', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIN ')),
                ('tel_mob', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE Mobile ')),
                ('tel_house', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE House ')),
                ('adresseemp', models.CharField(blank=True, max_length=50, null=True, verbose_name='ADRESSE EMPLOYE ')),
                ('credit_limitemp', models.FloatField(blank=True, default='0.0', null=True, verbose_name='CREDIT LIMIT')),
                ('accountemp', models.FloatField(blank=True, default='0.0', null=True, verbose_name='ACCOUNT')),
                ('statutemp', models.BooleanField(default=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
