# Generated by Django 5.0.3 on 2024-03-24 23:05

import psp_cash_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0009_alter_tbcotisation_typecotisation_tbemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbemploye',
            name='photo_profile',
            field=models.FileField(blank=True, null=True, upload_to=psp_cash_app.models.filepath),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.AlterField(
            model_name='tbemploye',
            name='sexeemp',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE EMPLOYE '),
        ),
    ]
