# Generated by Django 5.0.3 on 2024-03-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0013_alter_tbcotisation_typecotisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='activiteprofessionp',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='adressep',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='communep',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='departementp',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='lieunaissancep',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nifp',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='paysp',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='referencep',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='telephone1p',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='telephone2p',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='villep',
        ),
        migrations.AddField(
            model_name='membre',
            name='account',
            field=models.FloatField(blank=True, default='0.0', null=True, verbose_name='ACCOUNT'),
        ),
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ADRESSE EMPLOYE '),
        ),
        migrations.AddField(
            model_name='membre',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIN '),
        ),
        migrations.AddField(
            model_name='membre',
            name='credit_limit',
            field=models.FloatField(blank=True, default='0.0', null=True, verbose_name='CREDIT LIMIT'),
        ),
        migrations.AddField(
            model_name='membre',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF '),
        ),
        migrations.AddField(
            model_name='membre',
            name='tel_house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE HOUSE '),
        ),
        migrations.AddField(
            model_name='membre',
            name='tel_mob',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE MOBILE '),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
