# Generated by Django 5.0.3 on 2024-03-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0014_remove_membre_activiteprofessionp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbreceipt',
            fields=[
                ('num_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('num_bath', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero batch ')),
                ('client', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client ')),
                ('date_receipt', models.DateTimeField(auto_now=True, null=True)),
                ('total_article', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Article')),
                ('tax', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tax')),
                ('total_cost', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Cost')),
                ('total_price', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Price')),
                ('receipt_discount', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Receipt Discount')),
                ('balance', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Balance')),
                ('observation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observation ')),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut ')),
                ('deposit', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Deposit')),
                ('service_charge', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Service Charge')),
                ('type_receipt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type Receipt')),
                ('user_receipt', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ')),
                ('date_close', models.DateTimeField(verbose_name='Date Close (YYYY-MM-DD)')),
                ('close_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Close By ')),
            ],
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.CreateModel(
            name='tbpaiement',
            fields=[
                ('num_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date Paiement (YYYY-MM-DD)')),
                ('type_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de Paiement ')),
                ('montant', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Montant Paie')),
                ('tender', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tender')),
                ('day_rate', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Cost')),
                ('user_paie', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='tbreceiptarticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ligne', models.BigIntegerField(blank=True, default='1', null=True, verbose_name='Numero batch ')),
                ('quantite', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Article')),
                ('cout', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tax')),
                ('prix', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Cost')),
                ('discount_article', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Total Price')),
                ('receipt_discount', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Receipt Discount')),
                ('observation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observation ')),
                ('statut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut ')),
                ('user_added_byreceipt', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ')),
                ('date_added', models.DateTimeField(verbose_name='Date Added (YYYY-MM-DD)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbarticle')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbreceipt')),
            ],
        ),
    ]
