# Generated by Django 5.0.3 on 2024-03-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0015_tbreceipt_alter_membre_sexep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='close_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Close By'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='deposit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='num_bath',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero batch'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='observation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='receipt_discount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Receipt Discount'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='service_charge',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Service Charge'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='tax',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='total_article',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Article'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='total_cost',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='tbreceipt',
            name='user_receipt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='cout',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='discount_article',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='num_ligne',
            field=models.BigIntegerField(blank=True, default=1, null=True, verbose_name='Numero batch'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='observation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='prix',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='quantite',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Article'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='receipt_discount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Receipt Discount'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='tbreceiptarticle',
            name='user_added_byreceipt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User'),
        ),
    ]
