# Generated by Django 5.0.3 on 2024-03-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0016_alter_tbcotisation_typecotisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
    ]
