# Generated by Django 5.0.3 on 2024-03-28 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0017_alter_membre_sexep'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbreceipt',
            name='compagnie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
    ]
