# Generated by Django 5.0.3 on 2024-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0018_tbreceipt_compagnie_alter_membre_sexep'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbconfiguration',
            fields=[
                ('id_conf', models.AutoField(primary_key=True, serialize=False)),
                ('orther_curr_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Current Name ')),
                ('other_curr_symb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Current Symbole ')),
                ('other_curr_rate', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Other Current Rate ')),
                ('taxname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Name 1 ')),
                ('tax_rate1', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tax Rate 1 ')),
                ('taxname2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Name 2 ')),
                ('tax_rate2', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tax Rate 2 ')),
                ('taxname3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Name 3 ')),
                ('tax_rate3', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Tax Rate 3 ')),
                ('use_batch_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Use Batch Number')),
                ('curr_batch_num', models.IntegerField(blank=True, default='0', null=True, verbose_name='Current Batch Number')),
                ('nbctoprintonhold', models.IntegerField(blank=True, default='0', null=True, verbose_name='Nb C to Print on Hold')),
                ('nbctoprintonpayment', models.IntegerField(blank=True, default='0', null=True, verbose_name='Nb C to Print on Payment')),
            ],
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
