# Generated by Django 5.0.3 on 2024-04-01 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0020_alter_tbcotisation_typecotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbconfiguration',
            name='compagnie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
