# Generated by Django 4.2.5 on 2024-04-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0021_tbconfiguration_compagnie_alter_membre_sexep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='muso_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='compagnie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
