# Generated by Django 4.2.5 on 2024-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0022_remove_comment_muso_id_comment_compagnie_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbpayout',
            fields=[
                ('code_payout', models.AutoField(primary_key=True, serialize=False)),
                ('payout', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Payout ')),
                ('date_payout', models.DateTimeField(auto_now_add=True, verbose_name='Date Payout (YYYY-MM-DD)')),
                ('payout_comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observation')),
                ('userAdded', models.CharField(blank=True, max_length=50, null=True, verbose_name='User ')),
            ],
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
