# Generated by Django 4.2.5 on 2024-04-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psp_cash_app', '0023_tbpayout_alter_tbcotisation_typecotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbpayout',
            name='compagnie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='psp_cash_app.tbcompagnie'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
